### ISSUE TITLE
Call Forward

### ISSUE THREAD

**Issue by vyshakhbabji** [ringcentral/ringcentral-web-phone#13]
If clicked for outgoing call session :  this is the error you get-
Uncaught (in promise) TypeError: self.session.accept is not a function
    at http://localhost:63342/web-phone-1/build/ringcentral-web-phone.js:1138:22
    at PhoneLine.answer (http://localhost:63342/web-phone-1/build/ringcentral-web-phone.js:1118:12)
    at PhoneLine.forward (http://localhost:63342/web-phone-1/build/ringcentral-web-phone.js:1097:17)
    at forward (http://localhost:63342/web-phone-1/demo/index.js:156:14)

Fix the error msg.

**Comment by vyshakhbabji** [comment]
Fixed with promises
