### ISSUE TITLE
Call Flip

### ISSUE THREAD

**Issue by vyshakhbabji** [ringcentral/ringcentral-web-phone#8]
When not on call and you try to flip the call
Call is disconnected by user when the user is put on hold

Uncaught (in promise) Error: Not on call
    at PhoneLine.flip (http://localhost:63342/web-phone-1/build/ringcentral-web-phone.js:965:31)
    at callflip (http://localhost:63342/web-phone-1/demo/index.js:131:14)
    at HTMLInputElement.onclick (http://localhost:63342/web-phone-1/demo/index.html:154:87)

Fix the error message

**Comment by vyshakhbabji** [comment]
Fixed with promises
