### ISSUE TITLE
Start/Stop Recording

### ISSUE THREAD

**Issue by vyshakhbabji** [ringcentral/ringcentral-web-phone#9]
When not on call but sip registered.
When you muting or unmuting 
When press start/stop record
Could be handled with in app

TypeError: Cannot read property 'getAudioTracks' of undefined
    at setStreamMute (http://localhost:63342/web-phone-1/build/ringcentral-web-phone.js:1167:24)
    at PhoneLine.setMute (http://localhost:63342/web-phone-1/build/ringcentral-web-phone.js:1157:9)
    at Object.service.mute (http://localhost:63342/web-phone-1/build/ringcentral-web-phone.js:1559:22)
    at mute (http://localhost:63342/web-phone-1/demo/index.js:45:20)

Clean up the error msg

**Comment by vyshakhbabji** [comment]
Fixed with promises
